# Generated by Django 3.0.14 on 2022-01-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='emp_id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('middleName', models.CharField(db_column='middle_name', max_length=100, null=True)),
                ('dob', models.DateField()),
                ('salary', models.DecimalField(db_column='Emp_salary', decimal_places=6, max_digits=19)),
                ('dateOfJoining', models.DateField(db_column='date_of_joining')),
                ('deptId', models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('desId', models.ForeignKey(db_column='des_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.Designation')),
            ],
        ),
    ]
