# Generated by Django 3.0.14 on 2022-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='Des_id', primary_key=True, serialize=False)),
                ('designationName', models.CharField(db_column='Des_name', max_length=100)),
            ],
        ),
    ]
