# Generated by Django 3.0.14 on 2022-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(db_column='dept_name', max_length=100, unique=True)),
                ('deptContactPerson', models.CharField(db_column='dept_contact_person', max_length=100)),
            ],
        ),
    ]
